<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<UserSecretsId>f103f6a1-e17a-4586-b411-7f2b082eef6e</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Aspire\AppHost.ServiceDefaults\AppHost.ServiceDefaults.csproj" />
		<ProjectReference Include="..\..\Viblog\Viblog.csproj" />
	</ItemGroup>

	<Target Name="RemoveViblogRuntimeConfig" AfterTargets="Publish">
		<Delete Files="$(PublishDir)Viblog.runtimeconfig.json" />
	</Target>

</Project>
