<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-ViblogViblog-9812851b-d00e-4c01-9949-944fd4067437</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Auth0.AuthenticationApi" Version="7.45.0" />
    <PackageReference Include="Auth0.ManagementApi" Version="7.45.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="ColorCode.HTML" Version="2.0.15" />
    <PackageReference Include="Markdig" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="Telerik.UI.for.Blazor" Version="13.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aspire\AppHost.ServiceDefaults\AppHost.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Viblog.Data\Viblog.Data.AzureStorage\Viblog.Data.AzureStorage.csproj" />
    <ProjectReference Include="..\Viblog.Data\Viblog.Data.CosmosDb\Viblog.Data.CosmosDb.csproj" />
    <ProjectReference Include="..\Viblog.Infrastructure\Viblog.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Admin\Authentication\" />
    <Folder Include="Admin\Pages\Media\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
