# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ericjohansson

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

          # Add nuget source
      - name: Add NuGet source
  # --configfile './NuGet.Config' <-- Needed?
        run: dotnet nuget add source 'https://nuget.telerik.com/v3/index.json' --name 'TelerikOnlineFeed' --username 'api-key' --password '${{secrets.TELERIK_NUGET_KEY}}' --store-password-in-clear-text

      - name: Build with dotnet
        run: dotnet build Sample/EricJohansson.se/EricJohansson.se.csproj --configuration Release
        env:
          TELERIK_LICENSE: ${{ secrets.TELERIK_LICENSE_KEY }}

      - name: dotnet publish
        run: dotnet publish Sample/EricJohansson.se/EricJohansson.se.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
        env:
          TELERIK_LICENSE: ${{ secrets.TELERIK_LICENSE_KEY }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2CA872CBAE7F434F9D216F7836EF6048 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EFDC039FEAA14BCE966BF217ECB7EAEE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_646F132018444B64B69F59F03255487D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ericjohansson'
          slot-name: 'Production'
          package: .
          